channels:
- conda-forge
dependencies:
- python=3.9.9
- pip
- pip:
  - mlflow
  - cffi==1.15.0
  - lightgbm==3.3.1
  - matplotlib==3.4.3
  - pandas==1.3.4
  - typing-extensions==3.7.4.3
name: mlflow-env
